sudo: required
dist: trusty
language: python
python:
  - 3.5
install:
    - chmod +x ./script/deploy-docs.sh
    - chmod +x ./script/install-docs.sh
script:
    - ./script/install-docs.sh
    - ./script/deploy-docs.sh