language: python
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          sudo: required
          python: 3.5
          dist: trusty
        # Use generic language for osx
        - os: osx
          language: generic
install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm.sh | bash ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm-osx.sh | bash   ; fi
    - chmod +x ./script/deploy-docs.sh
    - chmod +x ./script/install-docs.sh
script:
    - premake gmake
    - python ./script/test-install.py
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./script/install-docs.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./script/deploy-docs.sh; fi