language: python
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          sudo: required
          python: 3.5
          dist: trusty
        # Use generic language for osx
        - os: osx
          osx_image: xcode7.3
          language: generic
        - os: osx
          osx_image: xcode8
          language: generic
install:
    - bash script/install-zpm-travis.sh
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./script/deploy-docs.sh && chmod +x ./script/install-docs.sh && ./script/install-docs.sh; fi
script:
    - python ./script/test-install.py
    - premake5 install-package
    - zpm install-package
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./script/deploy-docs.sh; fi
notifications:
    slack: zefiros:x8zCJkIy5iBNssvmgF0guTs3