language: python
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          sudo: required
          python: 3.5
          dist: trusty
        # Use generic language for osx
        - os: osx
          language: generic
install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm.sh | bash ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm-osx.sh | bash   ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./script/deploy-docs.sh && chmod +x ./script/install-docs.sh && ./script/install-docs.sh; fi
script:
    - python ./script/test-install.py
deploy:
  provider: script
  script: ./script/deploy-docs.sh
  on:
    branch: master