platform:
  - Win32
environment:
    PYTHON: "C:\\Python35"
build: off
install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - powershell -command "Invoke-WebRequest -Uri https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm.bat -OutFile %TEMP%/install-zpm.bat" && %TEMP%/install-zpm.bat && "SET PATH=%PATH%;%ALLUSERSPROFILE%/zpm"
test_script:
    - python ./script/test-install.py