site_name: ZPM
site_url: http://pm.zefiros.eu
repo_url: https://github.com/Zefiros-Software/ZPM
site_description: The C++ package manager based on premake5.
theme: united
copyright: Copyright © 2016 Mick van Duijn, Koen Visscher and Paul Visscher
google_analytics: ['UA-29999374-3', 'pm.zefiros.eu']
theme_dir: docs/style
pages: 
    - 'index.md'

    - 'Basics':
        - 'how-to-use.md'
        - 'Basics': 'basics/basics.md'
        - 'Registries': 'basics/registries.md'
        - 'Configuration': 'basics/config.md'
        - 'Adding': 
            - 'Packages': 'basics/manifest.md'
            - 'Assets': 'basics/assets.md'
            - 'Modules': 'basics/modules.md'
        - 'Commands': 
            - 'basics/commands.md'
            - 'Installing': 'basics/commands/install.md'
            - 'Updating': 'basics/commands/update.md'
            - 'Flags': 'basics/commands/flags.md'

    - 'Premake5': 
        - 'premake5/premake5.md'
        - 'Using': 'premake5/using.md'
        - 'Publishing Modules': 'premake5/publishing.md'

    - 'Packages': 
        - 'packages/packages.md'
        - 'General':
            - 'Versions': 'packages/general/versions.md'
            - 'Dev': 'packages/general/dev.md'
            - 'Overrides': 'packages/general/overrides.md'
            - '.package.json': 'packages/general/.package.md'
        - 'Using': 'packages/using.md'
        - '.build.json': 'packages/.build.md'

    - 'Assets': 
        - 'assets/assets.md'
        - 'Using': 'assets/using.md'
        - 'Publishing': 'assets/publishing.md'
    - 'Installer': 'installer/installer.md'


extra_css:
    - 'style/docs.css'

extra_javascript:
    - 'style/mathjax-loader.js'
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - toc:
        permalink: True
        separator: "_"
    - admonition
    - sane_lists
    - pymdownx.arithmatex
    - pymdownx.magiclink
    - markdown_checklist.extension